In [1]:
from glob import glob
from tqdm import tqdm
import json
import os
import pandas as pd
import numpy as np
import pickle
import sys

In [2]:
# 이미지, plotting 관련
# import matplotlib.pyplot as plt
# from skimage.io import imread
# from skimage.transform import resize
import tensorflow as tf

In [3]:
img_height, img_width = 224, 224  # 이미지 크기
batch_size = 8  # batch size 너무 크게하면 메모리 초과 뜸

In [4]:
data_loc = 'C:/Users/multicampus/projects/fresh/data'  # your data loc

In [5]:
train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    f'{data_loc}/Training/images',
    validation_split=0.2,
    subset="training",
    seed=123,  # random 값 고정
    image_size=(img_height, img_width),
    batch_size=batch_size)

FileNotFoundError: [WinError 3] 지정된 경로를 찾을 수 없습니다: 'C:/Users/multicampus/projects/fresh/data/Training/images'

In [6]:
val_ds = tf.keras.preprocessing.image_dataset_from_directory(
  f'{data_loc}/Training/images',
  validation_split=0.2,
  subset="validation",
  seed=123,
  image_size=(img_height, img_width),
  batch_size=batch_size)

Found 139067 files belonging to 54 classes.
Using 27813 files for validation.


In [ ]:
test_ds = tf.keras.preprocessing.image_dataset_from_directory(
    f'{data_loc}/Training/images',
    color_mode='rgb',
#     seed=123,
    image_size=(img_height, img_width),
    batch_size=batch_size)

In [70]:
temp = tf.keras.preprocessing.image_dataset_from_directory(
    f'{data_loc}/temp',
    color_mode='rgb',
#     seed=123,
    image_size=(img_height, img_width),
    batch_size=1)

Found 1 files belonging to 1 classes.


In [75]:
temp = cv2.imread(f'{data_loc}/temp/z/apple_fuji_L_1-1_1TOP.png')

In [76]:
temp[0]

array([[208, 204, 193],
       [208, 204, 193],
       [209, 203, 193],
       ...,
       [213, 208, 199],
       [214, 209, 200],
       [214, 209, 200]], dtype=uint8)

In [74]:
next(iter(temp))[0][0].numpy()

array([[[193., 204., 208.],
        [193., 204., 208.],
        [193., 203., 209.],
        ...,
        [199., 208., 213.],
        [200., 209., 214.],
        [200., 209., 214.]],

       [[196., 207., 211.],
        [194., 205., 209.],
        [195., 206., 210.],
        ...,
        [201., 210., 215.],
        [200., 209., 214.],
        [199., 208., 213.]],

       [[195., 206., 210.],
        [195., 206., 210.],
        [196., 207., 211.],
        ...,
        [201., 210., 215.],
        [200., 209., 214.],
        [201., 210., 215.]],

       ...,

       [[190., 201., 207.],
        [188., 199., 205.],
        [190., 200., 206.],
        ...,
        [193., 202., 208.],
        [193., 202., 209.],
        [194., 203., 210.]],

       [[190., 201., 207.],
        [189., 200., 206.],
        [189., 200., 206.],
        ...,
        [194., 203., 208.],
        [193., 202., 207.],
        [192., 201., 208.]],

       [[189., 200., 206.],
        [190., 201., 207.],
        [189., 2

In [8]:
import cv2

In [9]:
import numpy as np
from PIL import Image

In [ ]:
image = Image.open("lena.png")
np_array = np.array(image)

In [10]:
 def show_img(args):
#     for idx, img in enumerate(args):
#     cv2.imshow(f'winname{idx}', img)
    cv2.imshow('temp', args)
    cv2.waitKey()
    cv2.destroyAllWindows()

In [53]:
for a, b in test_ds:
    break

In [54]:
cls = train_ds.class_names

In [55]:
b

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([10, 47, 31, 44, 16, 28,  0,  8])>

In [38]:
cls[28]

'onion_white_M'

In [ ]:
a[1].numpy()

In [64]:
show_img(a[1].numpy().astype(np.uint8))

In [11]:
model = tf.keras.models.load_model("my_model_all.h5")

In [8]:
# train_ds.class_names

In [76]:
dir(train_ds)

['_GeneratorState',
 '__abstractmethods__',
 '__bool__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__nonzero__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_add_variable_with_custom_getter',
 '_apply_debug_options',
 '_as_serialized_graph',
 '_batch_size',
 '_checkpoint_dependencies',
 '_consumers',
 '_deferred_dependencies',
 '_drop_remainder',
 '_flat_shapes',
 '_flat_structure',
 '_flat_types',
 '_functions',
 '_gather_saveables_for_checkpoint',
 '_graph',
 '_graph_attr',
 '_handle_deferred_dependencies',
 '_input_dataset',
 '_inputs',
 '_list_extra_dependencies_for_serialization',
 '_list_functions_for_serialization',
 '_lookup_dependency',
 '_ma

In [9]:
num_classes = len(train_ds.class_names)

In [11]:
str(train_ds.class_names)

"['apple_fuji_L', 'apple_fuji_M', 'apple_fuji_S', 'apple_yanggwang_L', 'apple_yanggwang_M', 'apple_yanggwang_S', 'cabbage_green_L', 'cabbage_green_M', 'cabbage_green_S', 'cabbage_red_L', 'cabbage_red_M', 'cabbage_red_S', 'chinese-cabbage_L', 'chinese-cabbage_M', 'chinese-cabbage_S', 'garlic_uiseong_L', 'garlic_uiseong_M', 'garlic_uiseong_S', 'mandarine_hallabong_L', 'mandarine_hallabong_M', 'mandarine_hallabong_S', 'mandarine_onjumilgam_L', 'mandarine_onjumilgam_M', 'mandarine_onjumilgam_S', 'onion_red_L', 'onion_red_M', 'onion_red_S', 'onion_white_L', 'onion_white_M', 'onion_white_S', 'pear_chuhwang_L', 'pear_chuhwang_M', 'pear_chuhwang_S', 'pear_singo_L', 'pear_singo_M', 'pear_singo_S', 'persimmon_bansi_L', 'persimmon_bansi_M', 'persimmon_bansi_S', 'persimmon_booyu_L', 'persimmon_booyu_M', 'persimmon_booyu_S', 'persimmon_daebong_L', 'persimmon_daebong_M', 'persimmon_daebong_S', 'potato_seolbong_L', 'potato_seolbong_M', 'potato_seolbong_S', 'potato_sumi_L', 'potato_sumi_M', 'potato_su

In [12]:
f = open('./my_model_class.txt', 'w')
f.write(str(train_ds.class_names))
f.close()

In [14]:
# model = tf.keras.Sequential([
#   tf.keras.layers.Input(shape=(None, None, 3)),
#   tf.keras.layers.Resizing(500, 500),
#   tf.keras.layers.Conv2D(16, 3, padding='same', activation='relu', input_shape=(img_height, img_width, 3)),
#   tf.keras.layers.MaxPooling2D(),
#   tf.keras.layers.Conv2D(32, 3, padding='same', activation='relu'),
#   tf.keras.layers.MaxPooling2D(),
#   tf.keras.layers.Conv2D(32, 3, padding='same', activation='relu'),
#   tf.keras.layers.MaxPooling2D(),
#   tf.keras.layers.Conv2D(32, 3, padding='same', activation='relu'),
#   tf.keras.layers.MaxPooling2D(),
#   tf.keras.layers.Conv2D(32, 3, padding='same', activation='relu'),
#   tf.keras.layers.MaxPooling2D(),
#   tf.keras.layers.Flatten(),
#   tf.keras.layers.Dense(64, activation='relu'),
#   tf.keras.layers.Dense(num_classes)
# ])

In [82]:
model = tf.keras.Sequential([
#   tf.keras.layers.experimental.preprocessing.Rescaling(1./255, input_shape=(img_height, img_width, 3)),
  tf.keras.layers.Conv2D(16, 3, padding='same', activation='relu', input_shape=(img_height, img_width, 3)),
  tf.keras.layers.MaxPooling2D(),
  tf.keras.layers.Conv2D(32, 3, padding='same', activation='relu'),
  tf.keras.layers.MaxPooling2D(),
  tf.keras.layers.Conv2D(32, 3, padding='same', activation='relu'),
  tf.keras.layers.MaxPooling2D(),
  tf.keras.layers.Conv2D(32, 3, padding='same', activation='relu'),
  tf.keras.layers.MaxPooling2D(),
  tf.keras.layers.Conv2D(32, 3, padding='same', activation='relu'),
  tf.keras.layers.MaxPooling2D(),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(64, activation='relu'),
  tf.keras.layers.Dense(num_classes)
])

In [83]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_20 (Conv2D)           (None, 1000, 1000, 16)    448       
_________________________________________________________________
max_pooling2d_20 (MaxPooling (None, 500, 500, 16)      0         
_________________________________________________________________
conv2d_21 (Conv2D)           (None, 500, 500, 32)      4640      
_________________________________________________________________
max_pooling2d_21 (MaxPooling (None, 250, 250, 32)      0         
_________________________________________________________________
conv2d_22 (Conv2D)           (None, 250, 250, 32)      9248      
_________________________________________________________________
max_pooling2d_22 (MaxPooling (None, 125, 125, 32)      0         
_________________________________________________________________
conv2d_23 (Conv2D)           (None, 125, 125, 32)     

In [ ]:
y_ = np.concatenate([y_ for x, y_ in train_ds], axis=0)

In [ ]:
y_

In [116]:
type(train_ds)

tensorflow.python.data.ops.dataset_ops.BatchDataset

In [84]:
model.compile(
  optimizer='adam',
  loss=tf.losses.SparseCategoricalCrossentropy(from_logits=True),
  metrics=['accuracy'])

In [85]:
# model.summary()

In [88]:
model.fit(
  train_ds,
  validation_data=val_ds,
  epochs=5
)

Epoch 1/5
6954/6954 [==============================] - 4035s 580ms/step - loss: 0.3002 - accuracy: 0.8895 - val_loss: 0.6042 - val_accuracy: 0.8120
Epoch 2/5
6954/6954 [==============================] - 3697s 531ms/step - loss: 0.2726 - accuracy: 0.8997 - val_loss: 0.6512 - val_accuracy: 0.8080
Epoch 3/5
6954/6954 [==============================] - 3459s 497ms/step - loss: 0.2516 - accuracy: 0.9102 - val_loss: 0.6804 - val_accuracy: 0.8122
Epoch 4/5
6954/6954 [==============================] - 3459s 497ms/step - loss: 0.2239 - accuracy: 0.9193 - val_loss: 0.9779 - val_accuracy: 0.7578
Epoch 5/5
6954/6954 [==============================] - 3458s 497ms/step - loss: 0.2253 - accuracy: 0.9214 - val_loss: 0.7024 - val_accuracy: 0.8232


In [16]:
model.save('saved_model/my_model_no_scaled')

INFO:tensorflow:Assets written to: saved_model/my_model_no_scaled\assets


In [89]:
model.save('my_model_all2.h5')

## VGG

In [11]:
from keras.applications.vgg19 import VGG19
from keras.models import Model
from keras.layers import Dense, Dropout, Flatten

In [66]:
vgg_model = VGG19(
    weights = 'imagenet',
    # weights = None,
    include_top=False, input_shape=(img_height, img_width, 3))

In [67]:
x = vgg_model.output
x = Flatten()(x)
predictions = Dense(num_classes, activation='softmax')(x)

In [68]:
model = Model(inputs=vgg_model.input, outputs=predictions)

In [39]:
# 교육할 계층 설정 최상위 계층만 교육 (False 가중치 고정)
# for layer in vgg_model.layers:
#     layer.trainable = False

In [40]:
# 훈련할 레이어 확인
for layer in vgg_model.layers:
    print(layer, layer.trainable)

<keras.engine.input_layer.InputLayer object at 0x000001F99EC30D60> True
<keras.layers.convolutional.Conv2D object at 0x000001F99AF94DC0> True
<keras.layers.convolutional.Conv2D object at 0x000001F99AB87820> True
<keras.layers.pooling.MaxPooling2D object at 0x000001F99AB87550> True
<keras.layers.convolutional.Conv2D object at 0x000001F99AD63B50> True
<keras.layers.convolutional.Conv2D object at 0x000001F99AD68850> True
<keras.layers.pooling.MaxPooling2D object at 0x000001F99B5B6B20> True
<keras.layers.convolutional.Conv2D object at 0x000001F99AD67EE0> True
<keras.layers.convolutional.Conv2D object at 0x000001F99AD54BE0> True
<keras.layers.convolutional.Conv2D object at 0x000001F99B91AEE0> True
<keras.layers.convolutional.Conv2D object at 0x000001F99B925550> True
<keras.layers.pooling.MaxPooling2D object at 0x000001F99AD689D0> True
<keras.layers.convolutional.Conv2D object at 0x000001F99B9138E0> True
<keras.layers.convolutional.Conv2D object at 0x000001F99B913C40> True
<keras.layers.conv

In [69]:
model.compile(
  optimizer='adam',
  loss=tf.losses.SparseCategoricalCrossentropy(from_logits=True),
  metrics=['accuracy'])

In [82]:
model.fit(
  train_ds,
  validation_data=val_ds,
  epochs=5
)

Epoch 1/5
   77/55627 [..............................] - ETA: 21:15:40 - loss: 80.4937 - accuracy: 0.0195

KeyboardInterrupt: 

In [ ]:
model.save('vgg_19.h5')

## inception v3

In [20]:
import urllib
from keras.models import Model
from tensorflow.keras.applications.inception_v3 import InceptionV3
weights_url = "https://storage.googleapis.com/mledu-datasets/inception_v3_weights_tf_dim_ordering_tf_kernels_notop.h5"
weights_file = "inception_v3.h5"
urllib.request.urlretrieve(weights_url, weights_file)

# Model 초기화하기
pre_trained_model = InceptionV3(input_shape=(img_height, img_width, 3),
                                include_top=False,
                                weights=None)

# pre-trained weights 가져오기
pre_trained_model.load_weights(weights_file)

# layer를 freeze하기
for layer in pre_trained_model.layers:
    layer.trainable = False

# pre_trained_model.summary()

last_layer = pre_trained_model.get_layer('mixed7')
print('last layer output shape: ', last_layer.output_shape)
last_output = last_layer.output


#Output: last layer output shape: (None, 7, 7, 768)

last layer output shape:  (None, 60, 60, 768)


In [21]:
# 1 dimension의 output으로 flatten하기
x = tf.keras.layers.Flatten()(last_output)
# 1,024개의 hidden unit과 ReLU activation을 포함한 fully connected layer 추가
x = tf.keras.layers.Dense(128, activation='relu')(x)
# classification을 위한 마지막 sigmoid layer 추가하기
x = tf.keras.layers.Dense(num_classes)

model = Model(pre_trained_model.input, x)

ResourceExhaustedError: failed to allocate memory [Op:AddV2]

In [ ]:
model.compile(
  optimizer='adam',
  loss=tf.losses.SparseCategoricalCrossentropy(from_logits=True),
  metrics=['accuracy'])

In [ ]:
model.fit(
  train_ds,
  validation_data=val_ds,
  epochs=5
)

## Mobilenet

## Test set으로 check

In [77]:
model = tf.keras.models.load_model("my_model_all.h5")

In [17]:
pred = []
y = []

In [18]:
for b_x, b_y in tqdm(test_ds):
    pred.extend(model.predict(b_x).tolist())
    y.extend(b_y.numpy().tolist())

100%|██████████| 17384/17384 [1:14:45<00:00,  3.88it/s]  


In [20]:
pred[1][y[1]]

20.549030303955078

In [28]:
train_ds.class_names[10]

'cabbage_red_M'

In [ ]:
pred[0]

In [21]:
pred = np.array(pred)
y = np.array(y)

In [26]:
y[0]

10

In [ ]:
pred[0]

In [22]:
pred

array([[-48.27950668, -41.38546371, -24.87778664, ..., -31.95282745,
        -17.54436874,  -5.78543663],
       [-11.5453701 ,  -5.01635265, -16.99840736, ...,  -4.96550179,
        -11.1272068 ,  -0.29249549],
       [-18.76620102, -20.89482689, -12.35179615, ...,  -7.57679653,
         -0.59024936,   1.00283289],
       ...,
       [  3.57014537,  -5.9930644 , -11.04100704, ...,  -7.94087791,
        -21.04894638,  -2.45782161],
       [-28.04727936, -26.64917564, -11.61307335, ..., -26.87086868,
        -10.79084206,  -0.65182662],
       [-19.19737434, -17.50462723, -39.06735992, ...,  -7.01412535,
         -8.93679619,   2.59434247]])

In [23]:
pred_one = np.array([np.argmax(x) for x in pred])

In [24]:
np.mean(pred_one == y)

0.8911531851553568

In [78]:
import cv2

In [151]:
temp = cv2.imread('C:/Users/multicampus/projects/fresh/data/Validation/apple_fuji/apple_fuji_L/apple_fuji_L_77-21_1TOP.png')

In [159]:
temp_ = temp

In [176]:
temp = cv2.imread('C:/Users/multicampus/projects/fresh/ap1.jpg')

In [177]:
temp = temp.reshape(1, 1000, 1000, 3)

In [178]:
temp = temp[0][:,:,::-1]

In [179]:
show_img(temp)

In [167]:
show_img(temp_)

In [180]:
cls = train_ds.class_names

In [181]:
p = model.predict(temp.reshape(1, 1000, 1000, 3))

In [182]:
p = model.predict(temp.reshape(1, 1000, 1000, 3))

In [183]:
p.argmax()

42

In [184]:
p

array([[-30.195953  , -14.368767  , -13.566744  , -15.013156  ,
        -15.733794  , -13.444851  , -21.676735  , -21.687859  ,
        -19.050915  ,  -6.5106544 ,  -2.7450593 ,  -4.9742203 ,
         -5.518044  ,  -7.7682858 ,  -5.033553  , -22.009432  ,
        -10.38269   ,  -5.191831  ,  -4.2672744 ,  -4.878315  ,
         -9.087064  , -26.469185  , -18.820457  , -21.69956   ,
        -21.280243  , -20.857233  , -10.769884  , -23.277521  ,
        -17.110382  , -16.46796   , -31.666595  , -10.944205  ,
        -10.178623  , -29.854036  ,  -9.025803  , -16.55844   ,
        -23.792301  , -11.418669  , -18.871683  , -22.986645  ,
         -6.1964235 , -14.433662  ,  -0.82379997,  -3.3999038 ,
         -4.9827676 , -31.744528  , -21.975224  , -18.0409    ,
        -22.62581   , -18.291506  , -20.59886   , -29.272686  ,
        -18.674107  , -11.304717  ]], dtype=float32)

In [185]:
pd.DataFrame(p[0], cls).sort_values(0, ascending = False)

0
persimmon_daebong_L     -0.823800
cabbage_red_M           -2.745059
persimmon_daebong_M     -3.399904
mandarine_hallabong_L   -4.267274
mandarine_hallabong_M   -4.878315
cabbage_red_S           -4.974220
persimmon_daebong_S     -4.982768
chinese-cabbage_S       -5.033553
garlic_uiseong_S        -5.191831
chinese-cabbage_L       -5.518044
persimmon_booyu_M       -6.196424
cabbage_red_L           -6.510654
chinese-cabbage_M       -7.768286
pear_singo_M            -9.025803
mandarine_hallabong_S   -9.087064
pear_chuhwang_S        -10.178623
garlic_uiseong_M       -10.382690
onion_red_S            -10.769884
pear_chuhwang_M        -10.944205
radish_winter-radish_S -11.304717
persimmon_bansi_M      -11.418669
apple_yanggwang_S      -13.444851
apple_fuji_S           -13.566744
apple_fuji_M           -14.368767
persimmon_booyu_S      -14.433662
apple_yanggwang_L      -15.013156
apple_yanggwang_M      -15.733794
onion_white_S          -16.467960
pear_singo_S           -16.558439
onion_white_M          -17.110382
potato_seolbong_S      -18.040899
potato_sumi_M          -18.291506
radish_winter-radish_M -18.674107
mandarine_onjumilgam_M -18.820457
persimmon_bansi_S      -18.871683
cabbage_green_S        -19.050915
potato_sumi_S          -20.598860
onion_red_M            -20.857233
onion_red_L            -21.280243
cabbage_green_L        -21.676735
cabbage_green_M        -21.687859
mandarine_onjumilgam_S -21.699560
potato_seolbong_M      -21.975224
garlic_uiseong_L       -22.009432
potato_sumi_L          -22.625811
persimmon_booyu_L      -22.986645
onion_white_L          -23.277521
persimmon_bansi_L      -23.792301
mandarine_onjumilgam_L -26.469185
radish_winter-radish_L -29.272686
pear_singo_L           -29.854036
apple_fuji_L           -30.195953
pear_chuhwang_L        -31.666595
potato_seolbong_L      -31.744528

In [100]:
cls[42]

'persimmon_daebong_L'

In [99]:
p[0][24:27]

array([-21.280243, -20.857233, -10.769884], dtype=float32)

In [112]:
cls[p[0].argmax()]

'cabbage_red_S'

## Model save

## Unused

In [ ]:
# normalization_layer = tf.keras.layers.experimental.preprocessing.Rescaling(1./255)

# normalized_ds = train_ds.map(lambda x, y: (normalization_layer(x), y))
# image_batch, labels_batch = next(iter(normalized_ds))
# first_image = image_batch[0]
# # Notice the pixels values are now in `[0,1]`.
# print(np.min(first_image), np.max(first_image)) 

In [ ]:
# model = tf.keras.Sequential([
#   tf.keras.layers.experimental.preprocessing.Rescaling(1./255),
#   tf.keras.layers.Conv2D(32, 3, activation='relu'),
#   tf.keras.layers.MaxPooling2D(),
#   tf.keras.layers.Conv2D(32, 3, activation='relu'),
#   tf.keras.layers.MaxPooling2D(),
#   tf.keras.layers.Conv2D(32, 3, activation='relu'),
#   tf.keras.layers.MaxPooling2D(),
#   tf.keras.layers.Flatten(),
#   tf.keras.layers.Dense(6, activation='relu'),
#   tf.keras.layers.Dense(num_classes)
# ])

In [ ]:
# AUTOTUNE = tf.data.AUTOTUNE

# train_ds = train_ds.cache().prefetch(buffer_size=AUTOTUNE)